M48
; DRILL file {KiCad (6.0.7)} date Fri Sep  2 16:32:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-02T16:32:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X5.1654Y-3.7835
X5.3937Y-3.6614
X5.3937Y-4.2913
X5.5866Y-3.8189
X6.1732Y-3.7795
T0
M30
